In [55]:
import pandas as pd

In [56]:
df = pd.read_csv("batdongsan.csv", encoding="utf-8-sig")
df.head()

,Tên dự án,Giá,Diện tích,Phòng ngủ,Phòng vệ sinh,Vị trí,Địa chỉ chi tiết,id
0,ĐỘC QUYỀN! QUỸ NGOẠI GIAO CĐT MELODY LINH ĐÀM ...,"3,6 tỷ",68 m²,2,2,"Hoàng Mai, Hà Nội","Dự án Hà Nội Melody Residences, Đường Bằng Liệ...",41461905.0
1,"BÁN ĐẤT NỀN 180M2 TẠI NGUYỄN VĂN KÝ, LONG PHƯỚ...","2,8 tỷ",180 m²,NaN,NaN,"Long Thành, Đồng Nai","Đường Nguyễn Văn Ký, Xã Long Phước, Long Thành...",42520449.0
2,BÁN CẶP CĂN SIÊU VIP ĐẠI LỘ SAN HÔ VINHOMES OC...,61 tỷ,300 m²,NaN,NaN,"Văn Giang, Hưng Yên","Dự án The Empire - Vinhomes Ocean Park 2, Xã L...",42556249.0
3,"MỞ BÁN QUỸ CĂN VỊ TRÍ ĐẸP VÀ GIÁ RẺ NHẤT, KHÁC...","19,5 tỷ",75 m²,NaN,NaN,"Đông Anh, Hà Nội","Dự án Vinhomes Cổ Loa, Đường Cổ Loa, Xã Đông H...",42270918.0
4,ĐƠN GIÁ TỪ 148TR/M2 ĐẾN 160TR/M2. GỌI 0942 906...,Giá thỏa thuận,96 m²,NaN,NaN,"Đan Phượng, Hà Nội","Dự án Vinhomes Wonder City, Xã Tân Hội, Đan Ph...",42250064.0

In [57]:
import pandas as pd

# Đọc dữ liệu
df = pd.read_csv("batdongsan.csv", encoding="utf-8-sig")

# 1. Dữ liệu có ID: loại trùng theo 'id'
df_with_id = df[df["id"].notnull()]
df_with_id = df_with_id.drop_duplicates(subset="id", keep="first")

# 2. Dữ liệu không có ID: loại trùng theo 'Tên dự án'
df_no_id = df[df["id"].isnull()]
df_no_id = df_no_id.drop_duplicates(subset="Tên dự án", keep="first")

# 3. Gộp lại
df_cleaned = pd.concat([df_with_id, df_no_id]).reset_index(drop=True)

# 4. Kiểm tra lại
print("✅ Số dòng sau khi làm sạch:", len(df_cleaned))
print("🟢 Trùng ID còn không:", df_cleaned[df_cleaned["id"].notnull()].duplicated(subset="id").any())
print("🔵 Trùng Tên dự án (nếu ID NaN) còn không:", df_cleaned[df_cleaned["id"].isnull()].duplicated(subset="Tên dự án").any())

# (Tùy chọn) Xuất file sạch ra
df_cleaned.to_csv("batdongsan_cleaned.csv", index=False, encoding="utf-8-sig")

✅ Số dòng sau khi làm sạch: 3284
🟢 Trùng ID còn không: False
🔵 Trùng Tên dự án (nếu ID NaN) còn không: False

In [58]:
df_cleaned.head()

,Tên dự án,Giá,Diện tích,Phòng ngủ,Phòng vệ sinh,Vị trí,Địa chỉ chi tiết,id
0,ĐỘC QUYỀN! QUỸ NGOẠI GIAO CĐT MELODY LINH ĐÀM ...,"3,6 tỷ",68 m²,2,2,"Hoàng Mai, Hà Nội","Dự án Hà Nội Melody Residences, Đường Bằng Liệ...",41461905.0
1,"BÁN ĐẤT NỀN 180M2 TẠI NGUYỄN VĂN KÝ, LONG PHƯỚ...","2,8 tỷ",180 m²,NaN,NaN,"Long Thành, Đồng Nai","Đường Nguyễn Văn Ký, Xã Long Phước, Long Thành...",42520449.0
2,BÁN CẶP CĂN SIÊU VIP ĐẠI LỘ SAN HÔ VINHOMES OC...,61 tỷ,300 m²,NaN,NaN,"Văn Giang, Hưng Yên","Dự án The Empire - Vinhomes Ocean Park 2, Xã L...",42556249.0
3,"MỞ BÁN QUỸ CĂN VỊ TRÍ ĐẸP VÀ GIÁ RẺ NHẤT, KHÁC...","19,5 tỷ",75 m²,NaN,NaN,"Đông Anh, Hà Nội","Dự án Vinhomes Cổ Loa, Đường Cổ Loa, Xã Đông H...",42270918.0
4,ĐƠN GIÁ TỪ 148TR/M2 ĐẾN 160TR/M2. GỌI 0942 906...,Giá thỏa thuận,96 m²,NaN,NaN,"Đan Phượng, Hà Nội","Dự án Vinhomes Wonder City, Xã Tân Hội, Đan Ph...",42250064.0

In [59]:
df = df_cleaned.dropna(subset=["Phòng ngủ", "Phòng vệ sinh"], how='any')

In [60]:
# Xóa dòng nếu có giá trị "Không có" trong cột "Phòng ngủ" hoặc "Phòng vệ sinh"
df = df[~df["Phòng ngủ"].isin(["Không có thông tin"])]
df = df[~df["Phòng vệ sinh"].isin(["Không có thông tin"])]
df = df[~df["Phòng vệ sinh"].isin(["Không có thông tin WC"])]
df = df[~df["Phòng vệ sinh"].isin(["Không có thông tin phòng ngủ"])]

In [61]:
df.head()

,Tên dự án,Giá,Diện tích,Phòng ngủ,Phòng vệ sinh,Vị trí,Địa chỉ chi tiết,id
0,ĐỘC QUYỀN! QUỸ NGOẠI GIAO CĐT MELODY LINH ĐÀM ...,"3,6 tỷ",68 m²,2,2,"Hoàng Mai, Hà Nội","Dự án Hà Nội Melody Residences, Đường Bằng Liệ...",41461905.0
6,TIN GIÁ THẬT. EM HIỆP CHUYÊN BÁN CĂN HỘ LUMIER...,"8,9 tỷ","74,2 m²",2,2,"Quận 2, Hồ Chí Minh","Dự án Lumiere Riverside, Đường Võ Nguyên Giáp,...",41007787.0
7,"NHẬN NHÀ Ở HOẶC CHO THUÊ NGAY, CHIẾT KHẤU LÊN ...","2,72 tỷ","68,2 m²",2,2,"Dĩ An, Bình Dương","Dự án Phú Đông Sky Garden, Đường An Bình, Phườ...",41003332.0
10,"ĐỘC QUYỀN 10 CĂN TẦNG TRUNG VIEW HỒ, STUDIO - ...",Giá thỏa thuận,60 m²,2,2,"Đông Anh, Hà Nội","Dự án Imperia Cổ Loa, Xã Đông Hội, Đông Anh, H...",42095599.0
11,"1PN-2PN-3PN VINHOMES Q9 CẮT LỖ 500-1.2 TỶ, CAM...","2,65 tỷ",60 m²,2,2,"Quận 9, Hồ Chí Minh","Dự án Vinhomes Grand Park, Phường Long Thạnh M...",42543296.0

In [62]:
print(df.count())

Tên dự án           1872
Giá                 1872
Diện tích           1872
Phòng ngủ           1872
Phòng vệ sinh       1872
Vị trí              1872
Địa chỉ chi tiết    1865
id                   788
dtype: int64

In [63]:
df = df.dropna(subset=["Địa chỉ chi tiết"], how='any')

In [64]:
print(df.count())

Tên dự án           1865
Giá                 1865
Diện tích           1865
Phòng ngủ           1865
Phòng vệ sinh       1865
Vị trí              1865
Địa chỉ chi tiết    1865
id                   788
dtype: int64

In [65]:
df = df.drop(columns=["id"])

In [66]:
df.to_csv("batdongsan_pre.csv", index=False, encoding="utf-8-sig")