In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("batdongsan.csv", encoding="utf-8-sig")
df.head()

,Tên dự án,Giá,Diện tích,Phòng ngủ,Phòng vệ sinh,Vị trí,Địa chỉ chi tiết,id
0,ĐỘC QUYỀN! QUỸ NGOẠI GIAO CĐT MELODY LINH ĐÀM ...,"3,6 tỷ",68 m²,2,2,"Hoàng Mai, Hà Nội","Dự án Hà Nội Melody Residences, Đường Bằng Liệ...",41461905.0
1,"BÁN ĐẤT NỀN 180M2 TẠI NGUYỄN VĂN KÝ, LONG PHƯỚ...","2,8 tỷ",180 m²,NaN,NaN,"Long Thành, Đồng Nai","Đường Nguyễn Văn Ký, Xã Long Phước, Long Thành...",42520449.0
2,BÁN CẶP CĂN SIÊU VIP ĐẠI LỘ SAN HÔ VINHOMES OC...,61 tỷ,300 m²,NaN,NaN,"Văn Giang, Hưng Yên","Dự án The Empire - Vinhomes Ocean Park 2, Xã L...",42556249.0
3,"MỞ BÁN QUỸ CĂN VỊ TRÍ ĐẸP VÀ GIÁ RẺ NHẤT, KHÁC...","19,5 tỷ",75 m²,NaN,NaN,"Đông Anh, Hà Nội","Dự án Vinhomes Cổ Loa, Đường Cổ Loa, Xã Đông H...",42270918.0
4,ĐƠN GIÁ TỪ 148TR/M2 ĐẾN 160TR/M2. GỌI 0942 906...,Giá thỏa thuận,96 m²,NaN,NaN,"Đan Phượng, Hà Nội","Dự án Vinhomes Wonder City, Xã Tân Hội, Đan Ph...",42250064.0

In [4]:
import pandas as pd

# Đọc dữ liệu
df = pd.read_csv("batdongsan.csv", encoding="utf-8-sig")

# 1. Dữ liệu có ID: loại trùng theo 'id'
df_with_id = df[df["id"].notnull()]
df_with_id = df_with_id.drop_duplicates(subset="id", keep="first")

# 2. Dữ liệu không có ID: loại trùng theo 'Tên dự án'
df_no_id = df[df["id"].isnull()]
df_no_id = df_no_id.drop_duplicates(subset="Tên dự án", keep="first")

# 3. Gộp lại
df_cleaned = pd.concat([df_with_id, df_no_id]).reset_index(drop=True)

# 4. Kiểm tra lại
print("✅ Số dòng sau khi làm sạch:", len(df_cleaned))
print("🟢 Trùng ID còn không:", df_cleaned[df_cleaned["id"].notnull()].duplicated(subset="id").any())
print("🔵 Trùng Tên dự án (nếu ID NaN) còn không:", df_cleaned[df_cleaned["id"].isnull()].duplicated(subset="Tên dự án").any())

# (Tùy chọn) Xuất file sạch ra
df_cleaned.to_csv("batdongsan_cleaned.csv", index=False, encoding="utf-8-sig")

✅ Số dòng sau khi làm sạch: 3284
🟢 Trùng ID còn không: False
🔵 Trùng Tên dự án (nếu ID NaN) còn không: False

In [5]:
df_cleaned.head()

,Tên dự án,Giá,Diện tích,Phòng ngủ,Phòng vệ sinh,Vị trí,Địa chỉ chi tiết,id
0,ĐỘC QUYỀN! QUỸ NGOẠI GIAO CĐT MELODY LINH ĐÀM ...,"3,6 tỷ",68 m²,2,2,"Hoàng Mai, Hà Nội","Dự án Hà Nội Melody Residences, Đường Bằng Liệ...",41461905.0
1,"BÁN ĐẤT NỀN 180M2 TẠI NGUYỄN VĂN KÝ, LONG PHƯỚ...","2,8 tỷ",180 m²,NaN,NaN,"Long Thành, Đồng Nai","Đường Nguyễn Văn Ký, Xã Long Phước, Long Thành...",42520449.0
2,BÁN CẶP CĂN SIÊU VIP ĐẠI LỘ SAN HÔ VINHOMES OC...,61 tỷ,300 m²,NaN,NaN,"Văn Giang, Hưng Yên","Dự án The Empire - Vinhomes Ocean Park 2, Xã L...",42556249.0
3,"MỞ BÁN QUỸ CĂN VỊ TRÍ ĐẸP VÀ GIÁ RẺ NHẤT, KHÁC...","19,5 tỷ",75 m²,NaN,NaN,"Đông Anh, Hà Nội","Dự án Vinhomes Cổ Loa, Đường Cổ Loa, Xã Đông H...",42270918.0
4,ĐƠN GIÁ TỪ 148TR/M2 ĐẾN 160TR/M2. GỌI 0942 906...,Giá thỏa thuận,96 m²,NaN,NaN,"Đan Phượng, Hà Nội","Dự án Vinhomes Wonder City, Xã Tân Hội, Đan Ph...",42250064.0

In [13]:
df = df_cleaned.dropna(subset=["Phòng ngủ", "Phòng vệ sinh"], how='any')

In [14]:
df.head()

,Tên dự án,Giá,Diện tích,Phòng ngủ,Phòng vệ sinh,Vị trí,Địa chỉ chi tiết,id
0,ĐỘC QUYỀN! QUỸ NGOẠI GIAO CĐT MELODY LINH ĐÀM ...,"3,6 tỷ",68 m²,2,2,"Hoàng Mai, Hà Nội","Dự án Hà Nội Melody Residences, Đường Bằng Liệ...",41461905.0
6,TIN GIÁ THẬT. EM HIỆP CHUYÊN BÁN CĂN HỘ LUMIER...,"8,9 tỷ","74,2 m²",2,2,"Quận 2, Hồ Chí Minh","Dự án Lumiere Riverside, Đường Võ Nguyên Giáp,...",41007787.0
7,"NHẬN NHÀ Ở HOẶC CHO THUÊ NGAY, CHIẾT KHẤU LÊN ...","2,72 tỷ","68,2 m²",2,2,"Dĩ An, Bình Dương","Dự án Phú Đông Sky Garden, Đường An Bình, Phườ...",41003332.0
10,"ĐỘC QUYỀN 10 CĂN TẦNG TRUNG VIEW HỒ, STUDIO - ...",Giá thỏa thuận,60 m²,2,2,"Đông Anh, Hà Nội","Dự án Imperia Cổ Loa, Xã Đông Hội, Đông Anh, H...",42095599.0
11,"1PN-2PN-3PN VINHOMES Q9 CẮT LỖ 500-1.2 TỶ, CAM...","2,65 tỷ",60 m²,2,2,"Quận 9, Hồ Chí Minh","Dự án Vinhomes Grand Park, Phường Long Thạnh M...",42543296.0

In [15]:
print(df.count())

Tên dự án           2697
Giá                 2697
Diện tích           2697
Phòng ngủ           2697
Phòng vệ sinh       2697
Vị trí              2697
Địa chỉ chi tiết    2690
id                   788
dtype: int64

In [16]:
df = df.dropna(subset=["Địa chỉ chi tiết"], how='any')

In [17]:
print(df.count())

Tên dự án           2690
Giá                 2690
Diện tích           2690
Phòng ngủ           2690
Phòng vệ sinh       2690
Vị trí              2690
Địa chỉ chi tiết    2690
id                   788
dtype: int64

In [18]:
df.drop(columns="id")

,Tên dự án,Giá,Diện tích,Phòng ngủ,Phòng vệ sinh,Vị trí,Địa chỉ chi tiết
0,ĐỘC QUYỀN! QUỸ NGOẠI GIAO CĐT MELODY LINH ĐÀM ...,"3,6 tỷ",68 m²,2,2,"Hoàng Mai, Hà Nội","Dự án Hà Nội Melody Residences, Đường Bằng Liệ..."
6,TIN GIÁ THẬT. EM HIỆP CHUYÊN BÁN CĂN HỘ LUMIER...,"8,9 tỷ","74,2 m²",2,2,"Quận 2, Hồ Chí Minh","Dự án Lumiere Riverside, Đường Võ Nguyên Giáp,..."
7,"NHẬN NHÀ Ở HOẶC CHO THUÊ NGAY, CHIẾT KHẤU LÊN ...","2,72 tỷ","68,2 m²",2,2,"Dĩ An, Bình Dương","Dự án Phú Đông Sky Garden, Đường An Bình, Phườ..."
10,"ĐỘC QUYỀN 10 CĂN TẦNG TRUNG VIEW HỒ, STUDIO - ...",Giá thỏa thuận,60 m²,2,2,"Đông Anh, Hà Nội","Dự án Imperia Cổ Loa, Xã Đông Hội, Đông Anh, H..."
11,"1PN-2PN-3PN VINHOMES Q9 CẮT LỖ 500-1.2 TỶ, CAM...","2,65 tỷ",60 m²,2,2,"Quận 9, Hồ Chí Minh","Dự án Vinhomes Grand Park, Phường Long Thạnh M..."
...,...,...,...,...,...,...,...
3263,Bán nhà mặt phố cạnh Aeon Bình Tân 182 Đường 7...,"17,5 tỷ",80 m²,4,3,"Bình Tân, Hồ Chí Minh","182 Đường 7, Phường Bình Trị Đông B, Bình Tân,..."
3264,"CƠ HỘI CHO CÁC NHÀ ĐẦU TƯ LƯỚT SÓNG, MAY MẮN C...","4,65 tỷ",45 m²,4,4,"Thanh Trì, Hà Nội","Đường Thọ Am, Xã Liên Ninh, Thanh Trì, Hà Nội"
3265,"Phước Kiển Nhà Bè: Hạ giá thêm 400tr từ 6,5ty ...","6,1 tỷ",80 m²,4,4,"Nhà Bè, Hồ Chí Minh","Đường Lê Văn Lương, Xã Phước Kiển, Nhà Bè, Hồ ..."
3266,Chính chủ bán căn 2PN + 1 tòa S1.10 Vinhomes O...,"3,15 tỷ","69,2 m²",2,2,"Gia Lâm, Hà Nội","Dự án The Sapphire 1 - Vinhomes Ocean Park, Xã..."
3283,"GIỎ HÀNG CUỐI CÙNG QUỸ CĂN SUN SYMPHONY, CHIẾT...","4,2 tỷ","70,1 m²",2,2,"Sơn Trà, Đà Nẵng","Dự án Sun Symphony Residence, Đường Trần Hưng ..."

In [19]:
df.to_csv("batdongsan_pre.csv", index=False, encoding="utf-8-sig")